name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'graalvm'
          java-version: '21'
          cache: 'maven'

      # explicitly install Maven 3.8.8 because the gluon plugin does not work with newer versions
      # but the ubuntu image comes with a new maven version preinstalled
      - name: Install Maven 3.8.8
        run: |
          wget https://apache.org
          tar -xzf apache-maven-3.8.8-bin.tar.gz
          echo "$(pwd)/apache-maven-3.8.8/bin" >> $GITHUB_PATH

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build with Maven
        run: |
          # Verify the correct version is loaded in this step
          mvn -version
          mvn clean gluonfx:build
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: target/gluonfx/aarch64-linux-android/gvm/*.apk